IF OBJECT_ID('[EDM].[PR_CONS_TB_CONTROLE_CADASTRO_ALVO]', 'P') IS NULL
	EXEC('CREATE PROCEDURE [EDM].[PR_CONS_TB_CONTROLE_CADASTRO_ALVO] AS')
GO  
ALTER PROCEDURE [EDM].[PR_CONS_TB_CONTROLE_CADASTRO_ALVO]                    
AS          
BEGIN        
         
 SELECT            
   TOP (15 - (SELECT CASE WHEN COUNT(1) > 15 THEN 15  
     ELSE COUNT(1)        
    END        
   FROM TB_RF_CONTROLE_RECALCULO TRCR WITH (NOLOCK)         
   WHERE CD_STATUS = 'Processing'))        
  MAX(ID_TB_RFON_CONTROLE_CADASTRO) ID_TB_RFON_CONTROLE_CADASTRO,        
  -1 ID_CONTROLE_RECALCULO,        
  TRCC.COD_ATIVO,        
  MAX(TRCC.DT_EVENTO) DT_EVENTO,        
  '' NM_LOGIN,        
  '' NM_MAQUINA,        
  RTRIM(LTRIM(COALESCE(ATRF.COD_CETIP_21, ATRF.DESCRICAO_ATIVO)))  AS COD_CETIP_21,      
  ATRF.DATA_EMISSAO      
 FROM EDM.TB_RFON_CONTROLE_CADASTRO  TRCC WITH (NOLOCK)        
  LEFT JOIN ATIVOS_RF ATRF WITH (NOLOCK) ON ATRF.COD_ATIVO = TRCC.COD_ATIVO        
  LEFT JOIN ATIVOS ATIV WITH (NOLOCK) ON ATIV.COD_ATIVO = TRCC.COD_ATIVO        
 WHERE NOT EXISTS (SELECT 1         
   FROM TB_RF_CONTROLE_RECALCULO WITH (NOLOCK)         
     WHERE CD_STATUS = 'Processing'        
     AND COD_ATIVO = TRCC.COD_ATIVO)        
 GROUP BY         
  TRCC.COD_ATIVO,        
  ATRF.COD_CETIP_21,        
  ATRF.DESCRICAO_ATIVO,        
  ATIV.COD_TIPO_ATIVO,      
  ATRF.DATA_EMISSAO      
 HAVING        
  MAX(TRCC.DT_EVENTO) > ISNULL((SELECT MAX(DT_INICIO) DT_INICIO        
        FROM TB_RF_CONTROLE_RECALCULO WITH (NOLOCK)        
        WHERE COD_ATIVO = TRCC.COD_ATIVO)        
        , -1)        
  AND ATIV.COD_TIPO_ATIVO IN (5,6)        
  AND MAX(TRCC.DT_EVENTO) > DATEADD(MONTH, -1, GETDATE())--CONVERT(DATETIME, '2018-08-21 08:00:00.000', 102)      
  ORDER BY ATRF.DATA_EMISSAO DESC, MAX(TRCC.DT_EVENTO) DESC      
        
END  
 