CREATE TYPE edm.en_tipo_impacto AS ENUM
    ('PRECO', 'CADASTRO', 'PU_EVENTO', 'PU_HISTORICO');

ALTER TYPE log.en_status_mensagem
    OWNER TO ledm;

CREATE TABLE IF NOT EXISTS edm.TB_ASSINATURA_TIPO_IMPACTO (
  PK_ASSINATURA_IMPACTO SERIAL NOT NULL,
  FK_ASSINATURA INT NOT NULL,
  EN_TIPO_IMPACTO edm.en_tipo_impacto,
  ES_IMPACTADO bool,
  PRIMARY KEY (PK_ASSINATURA_IMPACTO),
  FOREIGN KEY (FK_ASSINATURA)
      REFERENCES edm.tb_assinatura (PK_ASSINATURAS),
  CONSTRAINT CONST_IMPACTO_PAPEL UNIQUE (FK_ASSINATURA, EN_TIPO_IMPACTO)
);

ALTER TABLE edm.TB_ASSINATURA_TIPO_IMPACTO
    OWNER TO ledm;