CREATE TABLE IF NOT EXISTS edm.TB_FILES(
	PK_FILES SERIAL NOT null PRIMARY KEY,
	ID_PROCESSAMENTO INTEGER,
	DT_CRIACAO TIMESTAMP,
	DT_ULTIMA_ATUALIZACAO TIMESTAMP
);

CREATE TABLE IF NOT EXISTS edm.TB_STATUS(
	PK_STATUS SERIAL NOT null PRIMARY KEY,
	ES_STATUS BOOLEAN,
	TP_STATUS_NAME VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS edm.TB_FILES_LOG(
	PK_FILES_LOG SERIAL NOT null PRIMARY KEY,
	FK_FILES INTEGER REFERENCES edm.TB_FILES(PK_FILES),
	FK_STATUS INTEGER REFERENCES edm.TB_STATUS(PK_STATUS),
	DT_CRIACAO TIMESTAMP,
	TX_MESSAGE_ERROR VARCHAR(100)
);