ALTER TABLE edm.TB_PRECOS ADD COLUMN VL_PAGAMENTO_JUROS DOUBLE PRECISION;
ALTER TABLE edm.TB_PRECOS ADD COLUMN  VL_PORCENTUAL_AMORTIZADO DOUBLE PRECISION;
ALTER TABLE edm.TB_PRECOS ADD COLUMN  vl_PORCENTUAL_JUROS_INCORPORADO DOUBLE PRECISION;