GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA edm TO ledm;

DO $$ BEGIN
	DROP TABLE IF EXISTS TB_CONTROLE_MENSAGEM;
	DROP TYPE IF EXISTS EN_STATUS1;
	DROP TYPE IF EXISTS EN_STATUS;
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS edm.EN_STATUS (
	ID_PK_STATUS SERIAL NOT null PRIMARY KEY,
	TX_NOME_STATUS VARCHAR(40)	
);

CREATE TABLE IF NOT EXISTS edm.TB_CONTROLE_MENSAGEM (
	IU_PK_TB_CONTROLE_MENSAGEM  SERIAL NOT null PRIMARY KEY,
	DH_PROCESSAMENTO TIMESTAMP,
	TP_MENSAGEM VARCHAR(15),
	CD_ID_PROCESSAMENTO VARCHAR(40),
	TX_MENSAGEM JSONB,
	ES_PROCESSAMENTO INTEGER REFERENCES edm.EN_STATUS(ID_PK_STATUS),
	ES_PROCESSAMENTO_BTG varchar(30)
	);

INSERT INTO edm.EN_STATUS VALUES (1, 'Arquivo recebido');
INSERT INTO edm.EN_STATUS VALUES (2, 'Erro');
INSERT INTO edm.EN_STATUS VALUES (3, 'Arquivo nao Processado');
INSERT INTO edm.EN_STATUS VALUES (4, 'Arquivo Processado' );

GRANT SELECT, INSERT, UPDATE, DELETE ON edm.tb_controle_mensagem TO ledm;

alter table edm.tb_controle_mensagem alter column ES_PROCESSAMENTO INTEGER REFERENCES edm.EN_STATUS(ID_PK_STATUS);